In [53]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import json
import requests
import gmaps
import os
import sys
import gmaps.geojson_geometries


sys.path.insert(0, "/Users/ianmacmoore/Desktop/ClassHomework/keys")

# Import API key
from api_keys import g_key
gmaps.configure(api_key=g_key)
g_key

'AIzaSyD9XkNOKVvigSy1J4ys528AlzIgeXXXx0g'

In [8]:
#Get main data from csv
history_df = pd.read_csv("./Output_Data/COV_Tracking_US_Summary_data_20200422.csv")
history_df.head()

,State,Positive,Negative,Recovered,Date_Checked,Death,Hospitalized,Total_Test_Results
0,AK,329,10790,168.0,2020-04-21T19:32:00Z,9.0,36.0,11119
1,AL,5342,43295,NaN,2020-04-22T13:35:00Z,191.0,730.0,48637
2,AR,2262,26795,849.0,2020-04-22T13:09:00Z,43.0,291.0,29057
3,AZ,5251,49901,1215.0,2020-04-22T03:46:00Z,208.0,NaN,55152
4,CA,33261,259645,NaN,2020-04-22T03:28:00Z,1268.0,NaN,292906

In [9]:
history_df['Lat'] = ""
history_df['Lng'] = ""

In [10]:
#Need to add State Long Name to search off of
state_abbr_file="Excel_Files/StateAbbreviation.csv"
state_abbr_df=pd.read_csv(state_abbr_file)
state_abbr_df = state_abbr_df[['State Abbreviation','State']]
#state_abbr_df

In [11]:

history_df.rename(columns={"State": "State Abbreviation"},inplace=True)
revised_history_df=pd.merge(state_abbr_df,history_df, on="State Abbreviation", how="right")
revised_history_df.columns

Index(['State Abbreviation', 'State', 'Positive', 'Negative', 'Recovered',
       'Date_Checked', 'Death', 'Hospitalized', 'Total_Test_Results', 'Lat',
       'Lng'],
      dtype='object')

In [46]:
# create a params dict that will be updated with new city each iteration
params = {"key": g_key}

# Loop through the cities_pd and run a lat/long search for each city
for index, row in revised_history_df.iterrows():
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"

    state = row['State']

    # update address key value
    params['address'] = f"{state}"

    # make request
    states_lat_lng = requests.get(base_url, params=params)
    
    # print the cities_lat_lng url, avoid doing for public github repos in order to avoid exposing key
    # print(cities_lat_lng.url)
    
    # convert to json
    states_lat_lng = states_lat_lng.json()

    revised_history_df.loc[index, "Lat"] = states_lat_lng["results"][0]["geometry"]["location"]["lat"]
    revised_history_df.loc[index, "Lng"] = states_lat_lng["results"][0]["geometry"]["location"]["lng"]

# Visualize to confirm lat lng appear
revised_history_df

,State Abbreviation,State,Positive,Negative,Recovered,Date_Checked,Death,Hospitalized,Total_Test_Results,Lat,Lng
0,AL,Alabama,5342,43295,NaN,2020-04-22T13:35:00Z,191.0,730.0,48637,32.3182,-86.9023
1,AK,Alaska,329,10790,168.0,2020-04-21T19:32:00Z,9.0,36.0,11119,64.2008,-149.494
2,AZ,Arizona,5251,49901,1215.0,2020-04-22T03:46:00Z,208.0,NaN,55152,34.0489,-111.094
3,AR,Arkansas,2262,26795,849.0,2020-04-22T13:09:00Z,43.0,291.0,29057,35.2011,-91.8318
4,CA,California,33261,259645,NaN,2020-04-22T03:28:00Z,1268.0,NaN,292906,36.7783,-119.418
5,CO,Colorado,10106,37360,NaN,2020-04-21T18:15:00Z,449.0,1880.0,47466,39.5501,-105.782
6,CT,Connecticut,20360,43832,NaN,2020-04-21T20:32:00Z,1423.0,NaN,64192,41.6032,-73.0877
7,DE,Delaware,2931,13725,565.0,2020-04-21T18:27:00Z,82.0,NaN,16656,38.9108,-75.5277
8,FL,Florida,27869,254471,NaN,2020-04-22T12:21:00Z,884.0,4401.0,282340,27.6648,-81.5158
9,GA,Georgia,20166,68259,NaN,2020-04-22T03:11:00Z,818.0,3885.0,88425,32.1656,-82.9001
10,HI,Hawaii,582,24760,437.0,2020-04-22T03:19:00Z,12.0,56.0,25342,19.8968,-155.583
11,ID,Idaho,1766,15964,710.0,2020-04-22T12:59:00Z,51.0,158.0,17730,44.0682,-114.742
12,IL,Illinois,33059,121938,NaN,2020-04-21T20:10:00Z,1468.0,NaN,154997,40.6331,-89.3985
13,IN,Indiana,12097,55167,NaN,2020-04-21T18:23:00Z,630.0,NaN,67264,40.2672,-86.1349
14,IA,Iowa,3641,23974,1293.0,2020-04-21T18:17:00Z,83.0,NaN,27615,41.878,-93.0977
15,KS,Kansas,2025,17076,NaN,2020-04-21T18:34:00Z,107.0,419.0,19101,39.0119,-98.4842
16,KY,Kentucky,3192,30136,1266.0,2020-04-22T03:19:00Z,171.0,1076.0,33328,37.8393,-84.27
17,LA,Louisiana,24854,117576,NaN,2020-04-21T18:44:00Z,1405.0,NaN,142430,30.9843,-91.9623
18,ME,Maine,888,14076,443.0,2020-04-21T20:28:00Z,36.0,139.0,14964,45.2538,-69.4455
19,MD,Maryland,14775,59442,981.0,2020-04-22T14:11:00Z,584.0,3325.0,74217,39.0458,-76.6413
20,MA,Massachusetts,41199,134173,NaN,2020-04-21T20:31:00Z,1961.0,NaN,175372,42.4072,-71.3824
21,MI,Michigan,32967,84259,3237.0,2020-04-21T20:05:00Z,2700.0,NaN,117226,44.3148,-85.6024
22,MN,Minnesota,2567,45130,1254.0,2020-04-21T19:06:00Z,160.0,629.0,47697,46.7296,-94.6859
23,MS,Mississippi,4716,47648,NaN,2020-04-21T20:10:00Z,183.0,858.0,52364,32.3547,-89.3985
24,MO,Missouri,5941,52019,NaN,2020-04-22T13:08:00Z,189.0,NaN,57960,37.9643,-91.8318
25,MT,Montana,437,10804,273.0,2020-04-22T12:33:00Z,12.0,59.0,11241,46.8797,-110.363
26,NE,Nebraska,1722,14957,NaN,2020-04-22T13:10:00Z,38.0,NaN,16679,41.4925,-99.9018
27,NV,Nevada,3937,29118,NaN,2020-04-22T12:27:00Z,163.0,NaN,33055,38.8026,-116.419
28,NH,New Hampshire,1491,13550,546.0,2020-04-22T13:10:00Z,42.0,206.0,15041,43.1939,-71.5724
29,NJ,New Jersey,92387,92439,NaN,2020-04-21T20:33:00Z,4753.0,NaN,184826,40.0583,-74.4057
30,NM,New Mexico,2072,38805,529.0,2020-04-22T03:10:00Z,65.0,306.0,40877,34.5199,-105.87
31,NY,New York,251690,397635,23887.0,2020-04-22T12:15:00Z,14828.0,57103.0,649325,40.7128,-74.006
32,NC,North Carolina,6951,76380,NaN,2020-04-21T19:50:00Z,213.0,NaN,83331,35.7596,-79.0193
33,ND,North Dakota,644,14343,214.0,2020-04-21T19:48:00Z,13.0,54.0,14987,47.5515,-101.002
34,OH,Ohio,13725,80989,NaN,2020-04-22T14:34:00Z,557.0,2779.0,94714,40.4173,-82.9071
35,OK,Oklahoma,2807,43019,1702.0,2020-04-22T14:01:00Z,164.0,588.0,45826,35.4676,-97.5164
36,OR,Oregon,2002,39126,NaN,2020-04-21T19:37:00Z,78.0,471.0,41128,43.8041,-120.554
37,PA,Pennsylvania,34528,132323,NaN,2020-04-21T18:21:00Z,1564.0,NaN,166851,41.2033,-77.1945
38,RI,Rhode Island,5500,33833,315.0,2020-04-21T19:59:00Z,171.0,576.0,39333,41.5801,-71.4774
39,SC,South Carolina,4608,37833,3317.0,2020-04-22T02:54:00Z,135.0,837.0,42441,33.8361,-81.1637
40,SD,South Dakota,1755,11060,824.0,2020-04-22T12:18:00Z,8.0,100.0,12815,43.9695,-99.9018
41,TN,Tennessee,7394,100788,3828.0,2020-04-21T19:53:00Z,157.0,760.0,108182,35.5175,-86.5804
42,TX,Texas,20196,185203,6486.0,2020-04-21T18:19:00Z,517.0,NaN,205399,31.9686,-99.9018
43,UT,Utah,3296,69062,888.0,2020-04-21T18:31:00Z,32.0,277.0,72358,39.321,-111.094
44,VT,Vermont,818,12293,1710.0,2020-04-21T18:54:00Z,40.0,NaN,13111,44.5588,-72.5778
45,VA,Virginia,9451,48903,1418.0,2020-04-21T19:26:00Z,324.0,1581.0,58354,37.4316,-78.6569
46,WA,Washington,12282,132749,NaN,2020-04-22T14:32:00Z,682.0,NaN,145031,47.7511,-120.74
47,WV,West Virginia,939,24897,330.0,2020-04-22T14:38:00Z,27.0,NaN,25836,38.5976,-80.4549
48,WI,Wisconsin,4620,47841,NaN,2020-04-21T19:12:00Z,242.0,1252.0,52461,43.7844,-88.7879
49,WY,Wyoming,322,7301,254.0,2020-04-22T02:15:00Z,6.0,52.0,7623,43.076,-107.29
50,DC,District of Columbia,3206,12296,645.0,2020-04-22T14:07:00Z,127.0,NaN,15502,38.9072,-77.0369

$Create gmaps figure, add "features" list to have a circle for each State, with radius 
scaled to size of positive tests

In [13]:
#(couldn't get this per thousand populace piece to work)

#pop_byState_df = pd.read_csv("./Output_Data/Census_State_Population_20200422.csv")
#revised_history_df = revised_history_df[['State','State Abbreviation','Positive','Negative','Recovered','Date_Checked','Death','Hospitalized','Total_Test_Results','Lat','Lng']]
#revised_history_df=pd.merge(history_df,pop_byState_df,on="State", how="left")
#revised_history_df.columns

In [49]:
positive = np.sqrt(revised_history_df['Positive']).astype(float)*1000
locations = revised_history_df[['Lat', 'Lng']]
#badLatLng = revised_history_df[revised_history_df['Lat']==37.2256]

#badLatLng = revised_history_df[revised_history_df['Lat'] == 37.2256].index
cleaned_history_df = revised_history_df

cleaned_history_df = cleaned_history_df.dropna(subset=['State'],inplace=True)


cleaned_history_df

,State Abbreviation,State,Positive,Negative,Recovered,Date_Checked,Death,Hospitalized,Total_Test_Results,Lat,Lng
0,AL,Alabama,5342,43295,NaN,2020-04-22T13:35:00Z,191.0,730.0,48637,32.3182,-86.9023
1,AK,Alaska,329,10790,168.0,2020-04-21T19:32:00Z,9.0,36.0,11119,64.2008,-149.494
2,AZ,Arizona,5251,49901,1215.0,2020-04-22T03:46:00Z,208.0,NaN,55152,34.0489,-111.094
3,AR,Arkansas,2262,26795,849.0,2020-04-22T13:09:00Z,43.0,291.0,29057,35.2011,-91.8318
4,CA,California,33261,259645,NaN,2020-04-22T03:28:00Z,1268.0,NaN,292906,36.7783,-119.418
5,CO,Colorado,10106,37360,NaN,2020-04-21T18:15:00Z,449.0,1880.0,47466,39.5501,-105.782
6,CT,Connecticut,20360,43832,NaN,2020-04-21T20:32:00Z,1423.0,NaN,64192,41.6032,-73.0877
7,DE,Delaware,2931,13725,565.0,2020-04-21T18:27:00Z,82.0,NaN,16656,38.9108,-75.5277
8,FL,Florida,27869,254471,NaN,2020-04-22T12:21:00Z,884.0,4401.0,282340,27.6648,-81.5158
9,GA,Georgia,20166,68259,NaN,2020-04-22T03:11:00Z,818.0,3885.0,88425,32.1656,-82.9001
10,HI,Hawaii,582,24760,437.0,2020-04-22T03:19:00Z,12.0,56.0,25342,19.8968,-155.583
11,ID,Idaho,1766,15964,710.0,2020-04-22T12:59:00Z,51.0,158.0,17730,44.0682,-114.742
12,IL,Illinois,33059,121938,NaN,2020-04-21T20:10:00Z,1468.0,NaN,154997,40.6331,-89.3985
13,IN,Indiana,12097,55167,NaN,2020-04-21T18:23:00Z,630.0,NaN,67264,40.2672,-86.1349
14,IA,Iowa,3641,23974,1293.0,2020-04-21T18:17:00Z,83.0,NaN,27615,41.878,-93.0977
15,KS,Kansas,2025,17076,NaN,2020-04-21T18:34:00Z,107.0,419.0,19101,39.0119,-98.4842
16,KY,Kentucky,3192,30136,1266.0,2020-04-22T03:19:00Z,171.0,1076.0,33328,37.8393,-84.27
17,LA,Louisiana,24854,117576,NaN,2020-04-21T18:44:00Z,1405.0,NaN,142430,30.9843,-91.9623
18,ME,Maine,888,14076,443.0,2020-04-21T20:28:00Z,36.0,139.0,14964,45.2538,-69.4455
19,MD,Maryland,14775,59442,981.0,2020-04-22T14:11:00Z,584.0,3325.0,74217,39.0458,-76.6413
20,MA,Massachusetts,41199,134173,NaN,2020-04-21T20:31:00Z,1961.0,NaN,175372,42.4072,-71.3824
21,MI,Michigan,32967,84259,3237.0,2020-04-21T20:05:00Z,2700.0,NaN,117226,44.3148,-85.6024
22,MN,Minnesota,2567,45130,1254.0,2020-04-21T19:06:00Z,160.0,629.0,47697,46.7296,-94.6859
23,MS,Mississippi,4716,47648,NaN,2020-04-21T20:10:00Z,183.0,858.0,52364,32.3547,-89.3985
24,MO,Missouri,5941,52019,NaN,2020-04-22T13:08:00Z,189.0,NaN,57960,37.9643,-91.8318
25,MT,Montana,437,10804,273.0,2020-04-22T12:33:00Z,12.0,59.0,11241,46.8797,-110.363
26,NE,Nebraska,1722,14957,NaN,2020-04-22T13:10:00Z,38.0,NaN,16679,41.4925,-99.9018
27,NV,Nevada,3937,29118,NaN,2020-04-22T12:27:00Z,163.0,NaN,33055,38.8026,-116.419
28,NH,New Hampshire,1491,13550,546.0,2020-04-22T13:10:00Z,42.0,206.0,15041,43.1939,-71.5724
29,NJ,New Jersey,92387,92439,NaN,2020-04-21T20:33:00Z,4753.0,NaN,184826,40.0583,-74.4057
30,NM,New Mexico,2072,38805,529.0,2020-04-22T03:10:00Z,65.0,306.0,40877,34.5199,-105.87
31,NY,New York,251690,397635,23887.0,2020-04-22T12:15:00Z,14828.0,57103.0,649325,40.7128,-74.006
32,NC,North Carolina,6951,76380,NaN,2020-04-21T19:50:00Z,213.0,NaN,83331,35.7596,-79.0193
33,ND,North Dakota,644,14343,214.0,2020-04-21T19:48:00Z,13.0,54.0,14987,47.5515,-101.002
34,OH,Ohio,13725,80989,NaN,2020-04-22T14:34:00Z,557.0,2779.0,94714,40.4173,-82.9071
35,OK,Oklahoma,2807,43019,1702.0,2020-04-22T14:01:00Z,164.0,588.0,45826,35.4676,-97.5164
36,OR,Oregon,2002,39126,NaN,2020-04-21T19:37:00Z,78.0,471.0,41128,43.8041,-120.554
37,PA,Pennsylvania,34528,132323,NaN,2020-04-21T18:21:00Z,1564.0,NaN,166851,41.2033,-77.1945
38,RI,Rhode Island,5500,33833,315.0,2020-04-21T19:59:00Z,171.0,576.0,39333,41.5801,-71.4774
39,SC,South Carolina,4608,37833,3317.0,2020-04-22T02:54:00Z,135.0,837.0,42441,33.8361,-81.1637
40,SD,South Dakota,1755,11060,824.0,2020-04-22T12:18:00Z,8.0,100.0,12815,43.9695,-99.9018
41,TN,Tennessee,7394,100788,3828.0,2020-04-21T19:53:00Z,157.0,760.0,108182,35.5175,-86.5804
42,TX,Texas,20196,185203,6486.0,2020-04-21T18:19:00Z,517.0,NaN,205399,31.9686,-99.9018
43,UT,Utah,3296,69062,888.0,2020-04-21T18:31:00Z,32.0,277.0,72358,39.321,-111.094
44,VT,Vermont,818,12293,1710.0,2020-04-21T18:54:00Z,40.0,NaN,13111,44.5588,-72.5778
45,VA,Virginia,9451,48903,1418.0,2020-04-21T19:26:00Z,324.0,1581.0,58354,37.4316,-78.6569
46,WA,Washington,12282,132749,NaN,2020-04-22T14:32:00Z,682.0,NaN,145031,47.7511,-120.74
47,WV,West Virginia,939,24897,330.0,2020-04-22T14:38:00Z,27.0,NaN,25836,38.5976,-80.4549
48,WI,Wisconsin,4620,47841,NaN,2020-04-21T19:12:00Z,242.0,1252.0,52461,43.7844,-88.7879
49,WY,Wyoming,322,7301,254.0,2020-04-22T02:15:00Z,6.0,52.0,7623,43.076,-107.29
50,DC,District of Columbia,3206,12296,645.0,2020-04-22T14:07:00Z,127.0,NaN,15502,38.9072,-77.0369

In [51]:
fig = gmaps.figure(center = (36.161,-95.736), zoom_level=4)
circles_layer = gmaps.drawing_layer(show_controls=False)
fig.add_layer(circles_layer)

circlesFeatures = []

for index,row in revised_history_df.iterrows():
    #variablize lat and lng to input to api call
    lat = row["Lat"]
    lng = row["Lng"]
    
    circlesFeatures.append(gmaps.Circle(
         [lat,lng], radius=positive[index],
         stroke_color='red', fill_color=(255, 0, 132)
     ))

circles_layer.features = circlesFeatures

fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
#troubleshoot locations
# Add marker layer ontop 
#marker_layer = gmaps.marker_layer(locations)

#fig.add_layer(marker_layer)
# Display figure
#fig

In [37]:
statesOfInterest = ["Minnesota","Colorado","Michigan"]
statesOfInterest_df = cleaned_history_df
#statesOfInterest_df.set_index('State',inplace=True)
statesOfInterest_df = statesOfInterest_df.loc[(statesOfInterest_df['State']=="Minnesota")|
                                             (statesOfInterest_df['State']=="Michigan")|
                                             (statesOfInterest_df['State']=="Colorado")]
statesOfInterest_df

,State Abbreviation,State,Positive,Negative,Recovered,Date_Checked,Death,Hospitalized,Total_Test_Results,Lat,Lng
5,CO,Colorado,10106,37360,NaN,2020-04-21T18:15:00Z,449.0,1880.0,47466,39.5501,-105.782
21,MI,Michigan,32967,84259,3237.0,2020-04-21T20:05:00Z,2700.0,NaN,117226,44.3148,-85.6024
22,MN,Minnesota,2567,45130,1254.0,2020-04-21T19:06:00Z,160.0,629.0,47697,46.7296,-94.6859

In [67]:
fig2 = gmaps.figure(center = (43.082135, -96.442695), zoom_level=5)
circles_layerSubset = gmaps.drawing_layer()
fig2.add_layer(circles_layerSubset)

circlesFeaturesSubset = []

for index,row in statesOfInterest_df.iterrows():
    #variablize lat and lng to input to api call
    lat = row["Lat"]
    lng = row["Lng"]
    
    circlesFeaturesSubset.append(gmaps.Circle(
         [lat,lng], radius=positive[index],
         stroke_color='red', fill_color='red', fill_opacity=0.5
     ))

circles_layerSubset.features = circlesFeaturesSubset

fig2

Figure(layout=FigureLayout(height='420px'))

In [61]:
us_states_geojson = gmaps.geojson_geometries.load_geometry('us-states')

fig3 = gmaps.figure(center = (36.161,-95.736), zoom_level=4)

gini_layer = gmaps.geojson_layer(
    us_states_geojson,
    fill_color='red',
    stroke_color='red',
    fill_opacity=0.5)
fig3.add_layer(gini_layer)
fig3

Figure(layout=FigureLayout(height='420px'))

In [56]:
gmaps.geojson_geometries.geometry_metadata('us-states')

{'description': 'US state boundaries',
 'source': 'http://eric.clst.org/Stuff/USGeoJSON'}